import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta
          name="langfuse-public-key"
          content={process.env.NEXT_PUBLIC_LANGFUSE_PUBLIC_KEY || ""}
        />
        <meta
          name="langfuse-host"
          content={process.env.NEXT_PUBLIC_LANGFUSE_HOST || "https://cloud.langfuse.com"}
        />
        <script
          src="http://localhost:8080/widget.js"
          data-api-url="http://localhost:8080"
          data-agent="default"
          defer></script>
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
